import {prepareProgram,executePrepared,waitRuntime,adminSnapshot} from './support/d109-console.js'
import fs from 'node:fs/promises'
import path from 'node:path'
import { expect, test } from './support/v2-test.js'

test('starts fresh completion credits immediately while locking the event, then refreshes to the poster', async ({ browser, demo }) => {
  const controller = await browser.newContext({ baseURL: demo.baseURL })
  const projection = await browser.newContext({ baseURL: demo.baseURL, viewport: { width: 1920, height: 1080 } })
  const admin = await controller.newPage(), screen = await projection.newPage()
  admin.on('dialog', dialog => dialog.accept())
  try {
    await admin.goto('/admin')
    await admin.getByLabel('账号', { exact: true }).fill(demo.credentials.admin.username)
    await admin.getByLabel('密码', { exact: true }).fill(demo.credentials.admin.password)
    await admin.getByRole('button', { name: '登录', exact: true }).click()
    await screen.goto('/screen?settings=1')
    await expect(screen.getByText('大屏实时已连接', { exact: true })).toBeVisible()
    await admin.getByLabel('开始模式', { exact: true }).selectOption('LIVE')
    await admin.getByRole('button', { name: '开始活动', exact: true }).click()
    await admin.getByRole('dialog').getByRole('button', { name: '确定', exact: true }).click()
    await expect(screen.getByRole('heading', { name: '星海集结' })).toBeVisible()
    await admin.getByRole('button', { name: '进入节目', exact: true }).click()
    await admin.getByRole('dialog').getByRole('button', { name: '确定', exact: true }).click()
    await waitRuntime(admin,'02 节目应援')
    await admin.getByRole('button', { name: '结束并播放片尾', exact: true }).click()
    await admin.getByRole('dialog').getByRole('button', { name: '确定', exact: true }).click()
    await waitRuntime(admin,'已完成')
    await expect(screen.locator('.closing-credits')).toHaveAttribute('data-phase', 'intro')
    await screen.waitForTimeout(6200)
    await expect(screen.locator('.closing-credits')).toHaveAttribute('data-phase', 'credits')
    await screen.reload()
    await expect(screen.locator('.closing-credits')).toHaveAttribute('data-phase', 'poster')
    expect(await screen.locator('.closing-credits').evaluate(el => el.getAnimations({ subtree: true }).length)).toBe(0)
  } finally { await controller.close(); await projection.close() }
})

test('plays current programme credits once, preserves rehearsal state and exposes every static page', async ({ browser, demo }) => {
  test.setTimeout(150_000)
  const directory = path.resolve('output/playwright/d108/credits')
  await fs.mkdir(directory, { recursive: true })
  const controller = await browser.newContext({ baseURL: demo.baseURL })
  const projection = await browser.newContext({ baseURL: demo.baseURL, viewport: { width: 1920, height: 1080 } })
  const admin = await controller.newPage(), screen = await projection.newPage()
  const errors: string[] = []
  await screen.clock.install()
  screen.on('pageerror', error => errors.push(error.message))
  admin.on('dialog', dialog => dialog.accept())
  try {
    await admin.goto('/admin')
    await admin.getByLabel('账号', { exact: true }).fill(demo.credentials.admin.username)
    await admin.getByLabel('密码', { exact: true }).fill(demo.credentials.admin.password)
    await admin.getByRole('button', { name: '登录', exact: true }).click()
    await admin.getByRole('button', { name: '载入本场节目单' }).click()
    await admin.getByLabel('第 1 项名称', { exact: true }).fill('星河序曲（审片）')
    await admin.getByLabel('第 1 项表演者', { exact: true }).fill('合成测试演出团队')
    await admin.getByRole('button', { name: '下移第 1 项', exact: true }).click()
    await admin.getByRole('button', { name: '移出第 3 项', exact: true }).click()
    await admin.getByRole('button', { name: '确认应用 24 项' }).click()
    await expect(admin.locator('.catalog-editor')).toHaveCount(0)
    await screen.goto('/screen?settings=1')
    await expect(screen.getByText('大屏实时已连接', { exact: true })).toBeVisible()
    await screen.getByRole('button', { name: '隐藏设置', exact: true }).click()
    await expect(screen.locator('.v2-signal')).toHaveCount(0)
    await admin.getByRole('button', { name: '开始活动', exact: true }).click()
    await admin.getByRole('dialog').getByRole('button', { name: '确定', exact: true }).click()
    await admin.getByRole('button',{name:'管理',exact:true}).click(); await admin.getByRole('button', { name: '03 谢幕准备', exact: true }).click()
    await admin.getByRole('button',{name:'管理',exact:true}).click(); await admin.getByRole('button', { name: '预览电影片尾', exact: true }).click()
    await admin.getByRole('dialog', {name:'确认操作'}).getByRole('button',{name:'确定',exact:true}).click()
    const credits = screen.locator('.closing-credits')
    await expect(credits).toHaveAttribute('data-phase', 'intro')
    await screen.waitForTimeout(2200)
    await screen.screenshot({ path: path.join(directory, 'intro-1920.png') })
    await expect(credits).toHaveAttribute('data-phase', 'credits', { timeout: 12_000 })
    const roll = screen.locator('.closing-credits__roll')
    await expect(roll.locator('.closing-credits__entry')).toHaveCount(18)
    await expect(roll.locator('.closing-credits__entry').nth(0)).toHaveAttribute('data-program-id', 'event2026-02')
    await expect(roll.locator('.closing-credits__entry').nth(1)).toContainText('星河序曲（审片）')
    await expect(roll.locator('.closing-credits__entry').nth(1)).toContainText('合成测试演出团队')
    await expect(roll).not.toContainText('夜航星')
    // Seek the actual browser animation; this does not change business state or dispatch fake events.
    await roll.evaluate(el => { const a = el.getAnimations()[0]!; a.currentTime = Number(a.effect!.getTiming().duration) * .2 })
    await screen.screenshot({ path: path.join(directory, 'roll-1920.png') })
    await admin.getByRole('button', { name: '全场暂停', exact: true }).click()
    // The existing stage contract withdraws a rehearsal projection on PAUSE.
    await expect(credits).toHaveCount(0)
    await admin.getByRole('button', { name: '恢复运行', exact: true }).click()
    await expect(credits).toHaveCount(0)
    await admin.getByRole('button',{name:'管理',exact:true}).click(); await admin.getByRole('button', { name: '预览电影片尾', exact: true }).click()
    await admin.getByRole('dialog', {name:'确认操作'}).getByRole('button',{name:'确定',exact:true}).click()
    await expect(credits).toHaveAttribute('data-phase', 'intro')
    await screen.waitForTimeout(6200)
    await expect(credits).toHaveAttribute('data-phase', 'credits')
    await screen.clock.fastForward(135000)
    await expect(credits).toHaveAttribute('data-phase', 'outro')
    await screen.clock.fastForward(18000)
    await expect(credits).toHaveAttribute('data-phase', 'settle')
    await screen.clock.fastForward(6000)
    await expect(credits).toHaveAttribute('data-phase', 'poster')
    await screen.screenshot({ path: path.join(directory, 'poster-1920.png') })
    expect(await credits.evaluate(el => el.getAnimations({ subtree: true }).length)).toBe(0)
    await waitRuntime(admin,'运行中')
    await screen.reload()
    await expect(credits).toHaveAttribute('data-phase', 'poster')
    await screen.goto('/screen?motion=reduced')
    await expect(credits).toHaveAttribute('data-phase', 'poster')
    await screen.getByRole('button', { name: '节目致谢' }).click()
    const seen: string[] = []
    for (let i = 0; i < 5; i++) {
      const entries = screen.locator('.closing-credits__grid article')
      seen.push(...await entries.evaluateAll(els => els.map(el => el.getAttribute('data-program-id')!)))
      for (const entry of await entries.all()) await expect(entry).toBeInViewport()
      await screen.screenshot({ path: path.join(directory, `static-page-${i + 1}.png`) })
      if (i < 4) await screen.getByRole('button', { name: '下一页', exact: true }).click()
    }
    expect(new Set(seen).size).toBe(18)
    expect(seen.at(-1)).toBe('event2026-22')
    await expect(screen.getByRole('button', { name: '下一页', exact: true })).toBeDisabled()
    expect(await credits.evaluate(el => el.getAnimations({ subtree: true }).length)).toBe(0)
    await screen.setViewportSize({ width: 1280, height: 720 })
    await screen.screenshot({ path: path.join(directory, 'static-1280.png') })
    await expect(screen.getByRole('button', { name: '回到终章' })).toBeInViewport()
    await screen.getByRole('button', { name: '回到终章' }).click()
    await screen.screenshot({ path: path.join(directory, 'poster-1280.png') })
    expect(errors).toEqual([])
  } finally { await controller.close(); await projection.close() }
})
