"""D-104: split the pinned Noto SC font into disjoint, locally served ranges.

Run build-mobile-font.py first. This tool never downloads assets. App builds use
the checked-in WOFF2/CSS and do not require Python or fontTools.
"""
import argparse
import hashlib
import importlib.util
import json
from pathlib import Path
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[1]
ASSETS = ROOT / 'frontend/src/assets/fonts'
MANIFEST = ASSETS / 'font-ranges.json'
CSS = ROOT / 'frontend/src/styles/mobile-font.css'


def sha(p):
    return hashlib.sha256(p.read_bytes()).hexdigest()


def unicode_ranges(points):
    spans = []
    for n in sorted(points):
        if spans and spans[-1][1] + 1 == n:
            spans[-1][1] = n
        else:
            spans.append([n, n])
    return ','.join(f'U+{a:X}' if a == b else f'U+{a:X}-{b:X}' for a, b in spans)


def css_face(filename, points):
    return '\n'.join(['@font-face {', '  font-family: "Welcome Sans SC";',
        f'  src: url("../assets/fonts/{filename}") format("woff2");',
        '  font-style: normal;', '  font-weight: 400 700;', '  font-display: swap;',
        f'  unicode-range: {unicode_ranges(points)};', '}'])


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--source', type=Path)
    parser.add_argument('--title-sources', type=Path)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    spec = importlib.util.spec_from_file_location('mobile_font', ROOT / 'scripts/build-mobile-font.py')
    core = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(core)
    if args.check:
        m = json.loads(MANIFEST.read_text(encoding='utf8'))
        covered = set()
        for item in m['notoFiles']:
            p = ASSETS / item['file']
            assert sha(p) == item['sha256'], p.name
            points = set(TTFont(p).getBestCmap())
            assert not covered.intersection(points), 'Overlapping font ranges'
            covered.update(points)
            assert unicode_ranges(points) == item['unicodeRange']
        assert len(covered) == m['coveredCodepoints']
        assert sha(CSS) == m['cssSha256']
        for item in m['titleFiles']:
            assert sha(ASSETS / item['file']) == item['sha256']
        print(json.dumps({'status': 'PASS', 'coveredCodepoints': len(covered), 'notoBytes': sum(i['bytes'] for i in m['notoFiles']), 'titleBytes': sum(i['bytes'] for i in m['titleFiles'])}))
        return
    assert args.source and args.title_sources, '--source and --title-sources required'
    assert sha(args.source) == core.SOURCE_SHA256, 'Unpinned Noto font'
    core_font = TTFont(core.ASSET)
    core_points = set(core_font.getBestCmap())
    all_points = set(TTFont(args.source).getBestCmap())
    remaining = sorted(all_points - core_points)
    chunks = [remaining[i:i + 384] for i in range(0, len(remaining), 384)]
    records = []
    faces = ['/* D-104: locally served Noto Sans SC. Disjoint ranges keep the UI core light.\n   Generated by scripts/build-font-ranges.py; OFL in /licenses/. */']
    def record(p, points):
        records.append({'file': p.name, 'bytes': p.stat().st_size, 'sha256': sha(p), 'unicodeRange': unicode_ranges(points), 'codepointCount': len(points)})
        faces.append(css_face(p.name, points))
    record(core.ASSET, core_points)
    for index, points in enumerate(chunks):
        font = TTFont(args.source, recalcTimestamp=False)
        opts = subset.Options()
        opts.recalc_timestamp = False
        opts.name_IDs = ['*']
        opts.name_languages = ['*']
        ss = subset.Subsetter(options=opts)
        ss.populate(unicodes=points)
        ss.subset(font)
        font = instantiateVariableFont(font, {'wght': (400, 400, 700)}, inplace=True)
        names = {1: 'Welcome Sans SC', 2: 'Regular', 3: f'WelcomeSansSC:2.004:range-{index}', 4: 'Welcome Sans SC', 6: 'WelcomeSansSC-Regular', 16: 'Welcome Sans SC', 17: 'Regular'}
        for entry in font['name'].names:
            if entry.nameID in names:
                entry.string = names[entry.nameID].encode(entry.getEncoding())
        font.flavor = 'woff2'
        output = ASSETS / f'welcome-sans-sc-{index:03}.woff2'
        font.save(output)
        record(output, set(font.getBestCmap()))
        if index % 10 == 0:
            print(f'FONT_RANGES {index + 1}/{len(chunks)}', flush=True)
    CSS.write_text('\n\n'.join(faces) + '\n', encoding='utf8')
    ox_source = args.title_sources / 'Oxanium.ttf'
    font = TTFont(ox_source, recalcTimestamp=False)
    font.flavor = 'woff2'
    ox_output = ASSETS / 'oxanium.woff2'
    font.save(ox_output)
    title_files = [{'file': p.name, 'bytes': p.stat().st_size, 'sha256': sha(p)} for p in [ASSETS / 'smiley-sans-oblique.woff2', ox_output]]
    manifest = {'family': 'Welcome Sans SC', 'upstreamFamily': 'Noto Sans SC', 'sourceSha256': core.SOURCE_SHA256, 'sourceUrl': core.SOURCE_URL, 'coveredCodepoints': len(all_points), 'chunkSize': 384, 'notoFiles': records, 'cssSha256': sha(CSS), 'titleFiles': title_files,
        'titleSources': {'smiley': {'version': '2.0.1', 'url': 'https://github.com/atelier-anchor/smiley-sans/releases/tag/v2.0.1', 'archiveSha256': sha(args.title_sources / 'smiley-sans-v2.0.1.zip')}, 'oxanium': {'commit': (args.title_sources / 'oxanium-commit.txt').read_text(encoding='utf-8-sig').strip(), 'sourceSha256': sha(ox_source), 'url': 'https://github.com/sevmeyer/oxanium'}},
        'license': 'OFL-1.1', 'fallback': 'Emoji, characters outside upstream coverage and failed font requests use the readable browser fallback.'}
    MANIFEST.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + '\n', encoding='utf8')
    print(json.dumps({'notoFiles': len(records), 'notoBytes': sum(i['bytes'] for i in records), 'titleBytes': sum(i['bytes'] for i in title_files)}))


if __name__ == '__main__':
    main()
